#! /bin/bash -eu
source config-offsite

export CRDS_CONTEXT=hst_0943.pmap
export SVM_QUALITY_TESTING=on


# config-run-container
DEV_HOME=${MOSAICML_HOME:-`pwd`}
mkdir -p $DEV_HOME
if [ ${DEV_HOME} != "none" ]; then
    MOUNTS="--mount type=bind,source=$DEV_HOME,target=/home/developer"
else
    MOUNTS = ""
fi

CRDS_SRC=${CRDS_PATH:-/grp/crds/hst}
READONLY=${CRDS_READONLY_CACHE:-0}

SVM_SHELL=rkein@dlhlalab1
SVM_IMG=/ifs/archive/dev/processing/hla/home/mburger/singlevisits/images_2021-10-06
SVM_SRC=`ssh ${SVM_SHELL}:${SVM_SRC}`
MOUNTS="${MOUNTS} --mount type=bind, source=${SVM_SRC},target=${DEV_HOME}/mosaic-ml/data/images_2021-10-06"

if [[ "$READONLY" == "0" && "$CRDS_SRC" != "/grp/crds/hst" ]]; then
    MOUNTS="${MOUNTS} --mount type=bind,source=${CRDS_SRC},target=/grp/crds/cache"
else
    MOUNTS="${MOUNTS} --mount type=bind,source=${CRDS_SRC},target=/grp/crds/cache,readonly"
fi

# -it -p 8888:8888    # for interactive debug and JupyterHub access.
# -m=10024m
mosaicml_docker_run_pars=${MOSAICML_DOCKER_RUN_PARS:-"-it"}

docker run ${mosaicml_docker_run_pars} --env DEV_HOME=$DEV_HOME --env $MOUNTS ${MOSAICML_DOCKER_IMAGE} /bin/bash